### ISSUE TITLE
Do not show the Submodels that are not fetched from the Repo/Registry because of authorization reasons.

### ISSUE THREAD

**Issue by aaronzi** [eclipse-basyx/basyx-aas-web-ui#124]
Currently, the Submodels are getting shown with no information but just the ID when the current user doesn't have permissions for these Submodels. Instead of showing the empty Submodels and exposing the IDs, the UI should handle this efficiently and shouldn't show these Submodels. This should only apply if the Submodels couldn't be fetched due to authorization reasons.

- Submodels that are not allowed to be accessed should have a lock symbol displayed and should be shown in a greyed out status
- Submodels that are missing from a repo/registry should have an exclamation mark icon next to them

**Comment by mdanish98** [comment]
#141
