### ISSUE TITLE
[FEATURE] AAS Web UI should be able to show the Technical Data Viewer in a tabular format like the Package Explorer.

### ISSUE THREAD

**Issue by JS-Aibel** [eclipse-basyx/basyx-aas-web-ui#21]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to see the Technical Data in a tabular format like it is done in the Package Explorer.
This is related to the question regarding Technical Data Viewer in the AAS Web UI https://github.com/eclipse-basyx/basyx-aas-web-ui/issues/12.

**Describe the solution you'd like**
The way the Package Explorer is solving a deeply nested structure is as follows.

1. Each submodel element collection (SMC) will show as a header. Either by its description or idshort.
2. A standalone grid table within each submodel element collection will show the SMCs properties.
3. Column names are stated only once at the top of the viewer.
4. For each subsection (SMC) the header will be indented (by one char?) to visualize that it is a subsection of the header above.
5. The table grid is never indented.
6. See picture as shown below.

![image](https://github.com/user-attachments/assets/06795556-3a28-4d12-8fa3-78dc164424aa)

**Describe alternatives you've considered**
Continue using Package Explorer.

**Comment by aaronzi** [comment]
Hi @JS-Aibel,

Would be a cool addition. If you want feel free to extend the [existing plugin](https://github.com/eclipse-basyx/basyx-aas-web-ui/blob/main/aas-web-ui/src/components/SubmodelPlugins/TechnicalData.vue) by that feature. Maybe a switch between both views.
