### ISSUE TITLE
[BUG] Jumping to referenced element not working properly

### ISSUE THREAD

**Issue by aaronzi** [eclipse-basyx/basyx-aas-web-ui#46]
**Describe the bug**
When using a ReferenceElement that references e.g. a Property, the jump to that element does not work as intended. The path to the correct SubmodelElement is set, but the path to the AAS is not updated, still showing the path to the AAS that contained the ReferenceElement used. The treeview is therefore also not showing the referenced element correctly.

**To Reproduce**
1. Start the `BaSyxMinimal` xample
2. In the UI, select the AAS with the idShort `SecondAAS`
3. Navigate to the `PropReference` ReferenceElement
4. Click on jump
5. See that the `aas` query parameter in the address bar is not being updated

**Expected behavior**
The AAS query in the address bar should be updated correctly. This will also fix the problem of the treeview not changing to the referenced element.

**BaSyx (please complete the following information):**
- BaSyx Version: V2.0.0
- BaSyx SDK: Java v2
- AAS Version: DotAAS V3

**BaSyx configuration**
https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples/BaSyxMinimal

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: Version 1.70.119 Chromium: 129.0.6668.70 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by seicke** [comment]
I can confirm the bug. But from my point of view the aas query parameter is not causing the bug. The aas query parameter gets updated.

Steps to reproduce the behavior:

1. Start the BaSyxMinimal example (just with other ports)
2. Selecting AAS with idShort 'SecondAAS'
3. Navigate to the PropReference ReferenceElement
```
http://localhost:3999/?aas=http://localhost:9981/shells/aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvc20vMjQxMV83MTYwXzAxMzJfNDUyMw&path=http://localhost:9981/submodels/aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvc20vMjQxMV83MTYwXzAxMzJfNDUyMw/submodel-elements/PropReference
```
![localhost_3999__aas=http___localhost_9981_shells_aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvc20vMjQxMV83MTYwXzAxMzJfNDUyMw path=http___localhost_9981_submodels_aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvc20vMjQxMV83MT](https://github.com/user-attachments/assets/f617ba9b-3eb2-425e-ad1b-048c96d4af2f)
5. Click on jump
```
http://localhost:3999/?aas=http://localhost:9981/shells/aHR0cHM6Ly9odHctYmVybGluLmRlL2lkcy9hYXMvZGVtb2Fhc3Yz&path=http://localhost:9981/submodels/aHR0cHM6Ly9odHctYmVybGluLmRlL2lkcy9zbS9kZW1vc3VibW9kZWx2Mw%253D%253D/submodel-elements/IntProp
```
![localhost_3999__aas=http___localhost_9981_shells_aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvc20vMjQxMV83MTYwXzAxMzJfNDUyMw path=http___localhost_9981_submodels_aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvc20vMjQxMV (1)](https://github.com/user-attachments/assets/ad4bbe54-7d46-4881-a298-92b1ce79d5d8)


AAS query parameter in the address bar is being updated:

<code>aas=http://localhost:9981/shells/aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvc20vMjQxMV83MTYwXzAxMzJfNDUyMw</code>
--> <code>aas=http://localhost:9981/shells/aHR0cHM6Ly9odHctYmVybGluLmRlL2lkcy9hYXMvZGVtb2Fhc3Yz</code>

As well as the path query parameter to the correct SubmodelElement:
<code>path=http://localhost:9981/submodels/aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvc20vMjQxMV83MTYwXzAxMzJfNDUyMw/submodel-elements/PropReference</code>
--> <code>path=http://localhost:9981/submodels/aHR0cHM6Ly9odHctYmVybGluLmRlL2lkcy9zbS9kZW1vc3VibW9kZWx2Mw%253D%253D/submodel-elements/IntProp</code>
