### ISSUE TITLE
[FEATURE] Use BaSyx AAS Web UI with FA³ST Service/Registry

### ISSUE THREAD

**Issue by sunshineRunner22** [eclipse-basyx/basyx-aas-web-ui#57]
**Describe the solution you'd like**
I would like to use BaSyx AAS Web UI together with an AAS repository and registry from FA³ST (https://github.com/FraunhoferIOSB/FAAAST-Service, https://github.com/FraunhoferIOSB/FAAAST-Registry).
I tried to get it to work, but can't connect from the Web UI to the FA³ST Service/Registry urls, I'm getting network errors.
I guess it's not compatible at the moment, as noted in the documentation: "The AAS Web UI is now only compatible with the components of BaSyx V2 and the Asset Administration Shell V3."

**Comment by aaronzi** [comment]
Hello @sunshineRunner22,

thank you for that suggestion. I would like that as well and this shouldn't be that difficult to try and fix. Is FA³ST following this flow when it comes to accessing data from the respective components?

![image](https://github.com/user-attachments/assets/b9f19947-9690-4b8b-b18d-4121310b7d87)

The AAS Web UI expects at least two configurations to work. The URL of the AAS Registry and the URL of the Submodel Registry. It starts by fetching AAS Descriptors from the AAS Registry, uses the endpoint from the descriptor to locate the AAS in an AAS Repository and then does the same for the Submodels referenced in the AAS by using the configured Submodel Registry.

Would that work with FA³ST the same way?

I actually never started FA³ST components before. Do they have a Swagger UI to see which endpoints are available?

**Comment by sunshineRunner22** [comment]
I don't know for sure if FA³ST is following the flow above, but it definitely provides an AAS and Submodel Registry (https://github.com/FraunhoferIOSB/FAAAST-Registry). 

The supported API calls for the FA³ST Registry can be found here: https://faaast-registry.readthedocs.io/en/latest/api/api.html
(and for FA³ST Service here: https://faaast-service.readthedocs.io/en/v0.5.0/endpoints/http_endpoint/)

Thank you!
